apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- services.yaml
images:
- name: gitops
  newName: geraldobl58/gitops
  newTag: 9806014b751b235d754f6d9ce411b083929064ea
